// This file is auto-generated by scripts/generate-poi-registry.ts
import type { POI } from "@/lib/types";
import type { Bbox, LatLon } from "@/lib/data/pois/utils";

export type CityDataset = {
  id: string;
  center: LatLon;
  bbox?: Bbox;
  loader: () => Promise<POI[]>;
};

export const countryDatasets: Record<string, () => Promise<POI[]>> = {
  AE: async () => (await import("./datasets/countries/AE.json")).default as POI[],
  AT: async () => (await import("./datasets/countries/AT.json")).default as POI[],
  AU: async () => (await import("./datasets/countries/AU.json")).default as POI[],
  BE: async () => (await import("./datasets/countries/BE.json")).default as POI[],
  BR: async () => (await import("./datasets/countries/BR.json")).default as POI[],
  CA: async () => (await import("./datasets/countries/CA.json")).default as POI[],
  CH: async () => (await import("./datasets/countries/CH.json")).default as POI[],
  CZ: async () => (await import("./datasets/countries/CZ.json")).default as POI[],
  DE: async () => (await import("./datasets/countries/DE.json")).default as POI[],
  DK: async () => (await import("./datasets/countries/DK.json")).default as POI[],
  ES: async () => (await import("./datasets/countries/ES.json")).default as POI[],
  FI: async () => (await import("./datasets/countries/FI.json")).default as POI[],
  FR: async () => (await import("./datasets/countries/FR.json")).default as POI[],
  GB: async () => (await import("./datasets/countries/GB.json")).default as POI[],
  GR: async () => (await import("./datasets/countries/GR.json")).default as POI[],
  HR: async () => (await import("./datasets/countries/HR.json")).default as POI[],
  HU: async () => (await import("./datasets/countries/HU.json")).default as POI[],
  IE: async () => (await import("./datasets/countries/IE.json")).default as POI[],
  IT: async () => (await import("./datasets/countries/IT.json")).default as POI[],
  JP: async () => (await import("./datasets/countries/JP.json")).default as POI[],
  KR: async () => (await import("./datasets/countries/KR.json")).default as POI[],
  MX: async () => (await import("./datasets/countries/MX.json")).default as POI[],
  NL: async () => (await import("./datasets/countries/NL.json")).default as POI[],
  NO: async () => (await import("./datasets/countries/NO.json")).default as POI[],
  NZ: async () => (await import("./datasets/countries/NZ.json")).default as POI[],
  PL: async () => (await import("./datasets/countries/PL.json")).default as POI[],
  PT: async () => (await import("./datasets/countries/PT.json")).default as POI[],
  SE: async () => (await import("./datasets/countries/SE.json")).default as POI[],
  SG: async () => (await import("./datasets/countries/SG.json")).default as POI[],
  TH: async () => (await import("./datasets/countries/TH.json")).default as POI[],
  TR: async () => (await import("./datasets/countries/TR.json")).default as POI[],
  US: async () => (await import("./datasets/countries/US.json")).default as POI[],
  ZA: async () => (await import("./datasets/countries/ZA.json")).default as POI[],
};

export const cityDatasets: Record<string, CityDataset> = {
  "amsterdam": {
    id: "amsterdam",
    center: { lat: 52.3683, lon: 4.8938 },
    bbox: { minLat: 52.2986, minLon: 4.8169, maxLat: 52.4517, maxLon: 4.9795 },
    loader: async () => (await import("./datasets/cities/amsterdam.json")).default as POI[],
  },
  "athens": {
    id: "athens",
    center: { lat: 37.9755, lon: 23.726 },
    bbox: { minLat: 37.8899, minLon: 23.6372, maxLat: 38.0521, maxLon: 23.8075 },
    loader: async () => (await import("./datasets/cities/athens.json")).default as POI[],
  },
  "auckland": {
    id: "auckland",
    center: { lat: -36.8522, lon: 174.7648 },
    bbox: { minLat: -36.915, minLon: 174.6916, maxLat: -36.7836, maxLon: 174.8351 },
    loader: async () => (await import("./datasets/cities/auckland.json")).default as POI[],
  },
  "bangkok": {
    id: "bangkok",
    center: { lat: 13.7473, lon: 100.5175 },
    bbox: { minLat: 13.6549, minLon: 100.4264, maxLat: 13.8495, maxLon: 100.6351 },
    loader: async () => (await import("./datasets/cities/bangkok.json")).default as POI[],
  },
  "barcelona": {
    id: "barcelona",
    center: { lat: 41.3875, lon: 2.1661 },
    bbox: { minLat: 41.3133, minLon: 2.0689, maxLat: 41.4726, maxLon: 2.2488 },
    loader: async () => (await import("./datasets/cities/barcelona.json")).default as POI[],
  },
  "berlin": {
    id: "berlin",
    center: { lat: 52.5152, lon: 13.3942 },
    bbox: { minLat: 52.423, minLon: 13.245, maxLat: 52.593, maxLon: 13.4936 },
    loader: async () => (await import("./datasets/cities/berlin.json")).default as POI[],
  },
  "brussels": {
    id: "brussels",
    center: { lat: 50.8492, lon: 4.3522 },
    bbox: { minLat: 50.7855, minLon: 4.2795, maxLat: 50.9147, maxLon: 4.4247 },
    loader: async () => (await import("./datasets/cities/brussels.json")).default as POI[],
  },
  "budapest": {
    id: "budapest",
    center: { lat: 47.4978, lon: 19.042 },
    bbox: { minLat: 47.4322, minLon: 18.9694, maxLat: 47.5653, maxLon: 19.114 },
    loader: async () => (await import("./datasets/cities/budapest.json")).default as POI[],
  },
  "cape-town": {
    id: "cape-town",
    center: { lat: -33.9248, lon: 18.423 },
    bbox: { minLat: -33.9918, minLon: 18.3547, maxLat: -33.858, maxLon: 18.4938 },
    loader: async () => (await import("./datasets/cities/cape-town.json")).default as POI[],
  },
  "copenhagen": {
    id: "copenhagen",
    center: { lat: 55.6765, lon: 12.5694 },
    bbox: { minLat: 55.6114, minLon: 12.4927, maxLat: 55.7403, maxLon: 12.6435 },
    loader: async () => (await import("./datasets/cities/copenhagen.json")).default as POI[],
  },
  "dubai": {
    id: "dubai",
    center: { lat: 25.1797, lon: 55.2442 },
    bbox: { minLat: 25.01, minLon: 55.067, maxLat: 25.3197, maxLon: 55.358 },
    loader: async () => (await import("./datasets/cities/dubai.json")).default as POI[],
  },
  "dublin": {
    id: "dublin",
    center: { lat: 53.3489, lon: -6.2589 },
    bbox: { minLat: 53.2849, minLon: -6.332, maxLat: 53.4124, maxLon: -6.1875 },
    loader: async () => (await import("./datasets/cities/dublin.json")).default as POI[],
  },
  "helsinki": {
    id: "helsinki",
    center: { lat: 60.1718, lon: 24.9411 },
    bbox: { minLat: 60.1062, minLon: 24.8594, maxLat: 60.2323, maxLon: 25.0161 },
    loader: async () => (await import("./datasets/cities/helsinki.json")).default as POI[],
  },
  "istanbul": {
    id: "istanbul",
    center: { lat: 41.0163, lon: 28.9909 },
    bbox: { minLat: 40.825, minLon: 28.89, maxLat: 41.126, maxLon: 29.175 },
    loader: async () => (await import("./datasets/cities/istanbul.json")).default as POI[],
  },
  "lisbon": {
    id: "lisbon",
    center: { lat: 38.7222, lon: -9.1362 },
    bbox: { minLat: 38.6583, minLon: -9.2084, maxLat: 38.7872, maxLon: -9.0735 },
    loader: async () => (await import("./datasets/cities/lisbon.json")).default as POI[],
  },
  "london": {
    id: "london",
    center: { lat: 51.5079, lon: -0.1236 },
    bbox: { minLat: 51.4269, minLon: -0.255, maxLat: 51.5913, maxLon: 0.0505 },
    loader: async () => (await import("./datasets/cities/london.json")).default as POI[],
  },
  "mexico-city": {
    id: "mexico-city",
    center: { lat: 19.4368, lon: -99.132 },
    bbox: { minLat: 19.3672, minLon: -99.2004, maxLat: 19.4998, maxLon: -99.0661 },
    loader: async () => (await import("./datasets/cities/mexico-city.json")).default as POI[],
  },
  "mumbai": {
    id: "mumbai",
    center: { lat: 19.0367, lon: 72.8567 },
    bbox: { minLat: 18.8717, minLon: 72.7537, maxLat: 19.2647, maxLon: 72.9815 },
    loader: async () => (await import("./datasets/cities/mumbai.json")).default as POI[],
  },
  "munich": {
    id: "munich",
    center: { lat: 48.144, lon: 11.574 },
    bbox: { minLat: 48.052, minLon: 11.453, maxLat: 48.2688, maxLon: 11.6747 },
    loader: async () => (await import("./datasets/cities/munich.json")).default as POI[],
  },
  "new-york": {
    id: "new-york",
    center: { lat: 40.7249, lon: -73.9953 },
    bbox: { minLat: 40.5249, minLon: -74.0945, maxLat: 40.86, maxLon: -73.899 },
    loader: async () => (await import("./datasets/cities/new-york.json")).default as POI[],
  },
  "oslo": {
    id: "oslo",
    center: { lat: 59.9123, lon: 10.7486 },
    bbox: { minLat: 59.8496, minLon: 10.6754, maxLat: 59.9782, maxLon: 10.8316 },
    loader: async () => (await import("./datasets/cities/oslo.json")).default as POI[],
  },
  "paris": {
    id: "paris",
    center: { lat: 48.8611, lon: 2.3458 },
    bbox: { minLat: 48.785, minLon: 2.237, maxLat: 48.9367, maxLon: 2.4433 },
    loader: async () => (await import("./datasets/cities/paris.json")).default as POI[],
  },
  "prague": {
    id: "prague",
    center: { lat: 50.0769, lon: 14.4365 },
    bbox: { minLat: 50.0119, minLon: 14.3654, maxLat: 50.139, maxLon: 14.51 },
    loader: async () => (await import("./datasets/cities/prague.json")).default as POI[],
  },
  "rio-de-janeiro": {
    id: "rio-de-janeiro",
    center: { lat: -22.9084, lon: -43.173 },
    bbox: { minLat: -22.9734, minLon: -43.2385, maxLat: -22.8423, maxLon: -43.1039 },
    loader: async () => (await import("./datasets/cities/rio-de-janeiro.json")).default as POI[],
  },
  "rome": {
    id: "rome",
    center: { lat: 41.895, lon: 12.4805 },
    bbox: { minLat: 41.7032, minLon: 12.2461, maxLat: 41.9778, maxLon: 12.569 },
    loader: async () => (await import("./datasets/cities/rome.json")).default as POI[],
  },
  "seoul": {
    id: "seoul",
    center: { lat: 37.5697, lon: 126.976 },
    bbox: { minLat: 37.5001, minLon: 126.9081, maxLat: 37.6337, maxLon: 127.0478 },
    loader: async () => (await import("./datasets/cities/seoul.json")).default as POI[],
  },
  "singapore": {
    id: "singapore",
    center: { lat: 1.3502, lon: 103.8183 },
    bbox: { minLat: 1.2852, minLon: 103.7531, maxLat: 1.418, maxLon: 103.8855 },
    loader: async () => (await import("./datasets/cities/singapore.json")).default as POI[],
  },
  "stockholm": {
    id: "stockholm",
    center: { lat: 59.328, lon: 18.0636 },
    bbox: { minLat: 59.2644, minLon: 17.9898, maxLat: 59.3907, maxLon: 18.1408 },
    loader: async () => (await import("./datasets/cities/stockholm.json")).default as POI[],
  },
  "sydney": {
    id: "sydney",
    center: { lat: -33.8679, lon: 151.2108 },
    bbox: { minLat: -33.9356, minLon: 151.1386, maxLat: -33.8016, maxLon: 151.28 },
    loader: async () => (await import("./datasets/cities/sydney.json")).default as POI[],
  },
  "tokyo": {
    id: "tokyo",
    center: { lat: 35.6778, lon: 139.7115 },
    bbox: { minLat: 35.5764, minLon: 139.5703, maxLat: 35.7795, maxLon: 139.8607 },
    loader: async () => (await import("./datasets/cities/tokyo.json")).default as POI[],
  },
  "toronto": {
    id: "toronto",
    center: { lat: 43.6526, lon: -79.3818 },
    bbox: { minLat: 43.5864, minLon: -79.4514, maxLat: 43.7205, maxLon: -79.3127 },
    loader: async () => (await import("./datasets/cities/toronto.json")).default as POI[],
  },
  "vienna": {
    id: "vienna",
    center: { lat: 48.2057, lon: 16.3732 },
    bbox: { minLat: 48.1411, minLon: 16.2999, maxLat: 48.2756, maxLon: 16.4495 },
    loader: async () => (await import("./datasets/cities/vienna.json")).default as POI[],
  },
  "warsaw": {
    id: "warsaw",
    center: { lat: 52.2286, lon: 21.0109 },
    bbox: { minLat: 52.1652, minLon: 20.9404, maxLat: 52.2944, maxLon: 21.0856 },
    loader: async () => (await import("./datasets/cities/warsaw.json")).default as POI[],
  },
  "zagreb": {
    id: "zagreb",
    center: { lat: 45.8159, lon: 15.9834 },
    bbox: { minLat: 45.7492, minLon: 15.9077, maxLat: 45.8824, maxLon: 16.0568 },
    loader: async () => (await import("./datasets/cities/zagreb.json")).default as POI[],
  },
  "zurich": {
    id: "zurich",
    center: { lat: 47.3742, lon: 8.5388 },
    bbox: { minLat: 47.2999, minLon: 8.4415, maxLat: 47.4472, maxLon: 8.6178 },
    loader: async () => (await import("./datasets/cities/zurich.json")).default as POI[],
  },
};
